FROM alpine:3.5

ENV KEEPALIVED_VERSION 1.3.5
ENV KEEPALIVED_MD5 9964d295ec9d34ed3408b57d28847b68

# https://www.lua.org/ftp/#source
ENV LUA_VERSION=5.3.3 \
	LUA_SHA1=a0341bc3d1415b814cc738b2ec01ae56045d64ef

# see http://sources.debian.net/src/haproxy/jessie/debian/rules/ for some helpful navigation of the possible "make" arguments
RUN set -x \
	\
	&& apk add --no-cache --virtual .build-deps \
		ca-certificates \
		gcc \
		libc-dev \
		linux-headers \
		make \
		openssl \
		openssl-dev \
		pcre-dev \
		readline-dev \
		tar \
		zlib-dev \
	\
# install Lua
	&& wget -O lua.tar.gz "https://www.lua.org/ftp/lua-$LUA_VERSION.tar.gz" \
	&& echo "$LUA_SHA1 *lua.tar.gz" | sha1sum -c \
	&& mkdir -p /usr/src/lua \
	&& tar -xzf lua.tar.gz -C /usr/src/lua --strip-components=1 \
	&& rm lua.tar.gz \
	&& make -C /usr/src/lua -j "$(getconf _NPROCESSORS_ONLN)" linux \
	&& make -C /usr/src/lua install \
# put things we don't care about into a "trash" directory for purging
		INSTALL_BIN='/usr/src/lua/trash/bin' \
		INSTALL_CMOD='/usr/src/lua/trash/cmod' \
		INSTALL_LMOD='/usr/src/lua/trash/lmod' \
		INSTALL_MAN='/usr/src/lua/trash/man' \
# ... and since it builds static by default, put those bits somewhere we can purge after we build haproxy
		INSTALL_INC='/usr/local/lua-install/inc' \
		INSTALL_LIB='/usr/local/lua-install/lib' \
	&& rm -rf /usr/src/lua \
	\
# install KEEPALIVED
	&& wget -O keepalived.tar.gz "http://www.keepalived.org/software/keepalived-${KEEPALIVED_VERSION}.tar.gz" \
	&& echo "$KEEPALIVED_MD5 *keepalived.tar.gz" | md5sum -c \
  && tar xzvf keepalived.tar.gz \
	&& cd keepalived-${KEEPALIVED_VERSION} \
	&& ./configure \
	&& make \
	&& make install

RUN apk add --update curl jq	bash vim

COPY config config
RUN chmod -R +x config
RUN touch /var/run/haproxy.pid




#CMD ["bash", "-c", "/config/endpoints_script.sh"]
CMD ["bash", "-c", "/config/dummy.sh"]
